#!/usr/bin/env bash
# This script displays the username, user ID and home directory from /etc/passwd
while IFS=: read -r user pass uid gid info home shell
do
    echo "$user:$uid:$home"
done < /etc/passwd
